<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPSf1MNt\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPSf1MNt/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPSf1MNt.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPSf1MNt\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPSf1MNt\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PSf1MNt',
    'container.build_id' => '2c1e6910',
    'container.build_time' => 1612297910,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPSf1MNt');
